#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/sbin/rootd`
case "$1" in
  start)
  stat_busy "Starting ROOT file server daemon"
    [ -z "$PID" ] && /usr/bin/rootd >>/var/log/root.log 2>&1
    if [ $? -gt 0 ]; then
      stat_fail
    else
      PID=`pidof -o %PPID /usr/sbin/rootd`
      echo $PID >/var/run/rootd.pid
      add_daemon rootd
      stat_done
    fi
    ;;
  stop)
  stat_busy "Stopping ROOT file server daemon"
    [ ! -z "$PID" ]  && kill $PID &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon rootd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
