# Maintainer: Guoyi Zhang <guoyizhang at malacology dot net>

_pkgname=insight
_pkgver=1.4.5
pkgname=r-${_pkgname,,}
pkgver=${_pkgver//-/.}
pkgrel=1
pkgdesc="Easy Access to Model Information for Various Model Objects"
arch=(any)
url="https://cran.r-project.org/package=$_pkgname"
license=('GPL-3.0-only')
depends=(
  r
)
optdepends=(
  r-aer
  r-afex
  r-aod
  r-ape
  r-bayesfactor
  r-bayestestr
  r-bbmle
  r-bdsmatrix
  r-betareg
  r-bh
  r-lcmm
  r-biglm
  r-blavaan
  r-blme
  r-brms
  r-broom
  r-car
  r-cardata
  r-censreg
  r-cgam
  r-clubsandwich
  r-cobalt
  r-coxme
  r-cplm
  r-crch
  r-curl
  r-datawizard
  r-dbarts
  r-effectsize
  r-emmeans
  r-epir
  r-estimatr
  r-feisr
  r-fixest
  r-fungible
  r-fwb
  r-gam
  r-gamlss
  r-gamlss.data
  r-gamm4
  r-gbm
  r-gee
  r-geepack
  r-geor
  r-glmmadaptive
  r-glmmtmb
  r-glmtoolbox
  r-gmnl
  r-gt
  r-httptest2
  r-httr2
  r-interp
  r-ivreg
  r-jm
  r-knitr
  r-lavaan
  r-lavasearch2
  r-lfe
  r-lme4
  r-lmertest
  r-lmtest
  r-logistf
  r-logitr
  r-marginaleffects
  r-mclogit
  r-mclust
  r-mcmcglmm
  r-mertools
  r-metabma
  r-metadat
  r-metafor
  r-metaplus
  r-mice
  r-mhurdle
  r-mlogit
  r-mmrm
  r-modelbased
  r-multgee
  r-mumin
  r-mvtnorm
  r-nestedlogit
  r-nonnest2
  r-ordinal
  r-parameters
  r-parsnip
  r-pbkrtest
  r-performance
  r-phylolm
  r-plm
  r-proreg
  r-pscl
  r-psych
  r-quantreg
  r-rcpp
  r-rcppeigen
  r-recipes
  r-rmarkdown
  r-rms
  r-robustbase
  r-robustlmm
  r-rstanarm
  r-rstantools
  r-rstudioapi
  r-sampleselection
  r-sandwich
  r-serp
  r-sdmtmb
  r-speedglm
  r-statmod
  r-survey
  r-svylme
  r-testthat
  r-tidymodels
  r-tinytable
  r-tmb
  r-truncreg
  r-tweedie
  r-vgam
  r-weightit
  r-withr
  r-workflows
  r-tune
  r-rwiener
)
source=("https://cran.r-project.org/src/contrib/${_pkgname}_${_pkgver}.tar.gz")
md5sums=('9ab3c366500a6b5af9ec6bbb4b4cf336')
b2sums=('42b4f1cba7564376a51b31a55beab3db9c48111745b95bc234b068424ca29b59d04d354dbe5b8b97cbeb648013913e0cf84ff5b60256d2edc5a2e99d93279963')

build() {
  mkdir build
  R CMD INSTALL -l build "$_pkgname"
}

package() {
  install -d "$pkgdir/usr/lib/R/library"
  cp -a --no-preserve=ownership "build/$_pkgname" "$pkgdir/usr/lib/R/library"
}
