#!/usr/bin/env bash
##############################################################################
# HDF Viewer Wrapper
##############################################################################

# Configure appropriate fallback values:
HDFVIEW_APPLICATION="${HDFVIEW_APPLICATION:-/usr/bin/hdfview.sh}"
HDFVIEW_FONT_PATH="${HDFVIEW_FONT_PATH:-/usr/share/fonts/truetype}"
HDFVIEW_FONT_TYPE="${HDFVIEW_FONT_TYPE:-$(fc-match --format '%{family}' sans)}"
HDFVIEW_FONT_SIZE="${HDFVIEW_FONT_SIZE:-12}"
HDFVIEW_ANTIALIAS="${HDFVIEW_ANTIALIAS:-on}"
HDFVIEW_LOOK_FEEL="${HDFVIEW_LOOK_FEEL:-com.sun.java.swing.plaf.gtk.GTKLookAndFeel}"

# Glob for configuration files:
HDFVIEW_CFG_FILES=$(echo ~/.hdfview[0-9]*.[0-9]*)

# Attempt to fix fonts:
sed -i -r "s|^(font\.size)=.*\$|\\1=${HDFVIEW_FONT_SIZE}|" ${HDFVIEW_CFG_FILES}
sed -i -r "s|^(font\.type)=.*\$|\\1=${HDFVIEW_FONT_TYPE}|" ${HDFVIEW_CFG_FILES}
export JAVA_FONTS="${FONT_PATH}"

# Attempt to fix look and feel:
JAVA_OPTIONS=(
    "-Dawt.useSystemAAFontSettings=${HDFVIEW_ANTIALIAS}"
    "-Dswing.defaultlaf=${HDFVIEW_LOOK_FEEL}"
    "-Dswing.crossplatformlaf=${HDFVIEW_LOOK_FEEL}"
)
JAVA_OPTIONS=$(printf ' %s' "${JAVA_OPTIONS[@]}")
JAVA_OPTIONS=${JAVA_OPTIONS:1}
export _JAVA_OPTIONS=${JAVA_OPTIONS}

# Launch the viewer:
exec ${HDFVIEW_APPLICATION} "${@}"

##############################################################################
# vim:et:ft=sh:nowrap:sts=4:sw=4:ts=4
