_PYVER := $(shell python -c 'import sys; print("%s.%s" %sys.version_info[0:2])')
_PYMAJ := $(shell python -c 'import sys; print("%s" %sys.version_info[0])')
_OCVMAJ := $(shell opencv_version | awk -F'.' '{ print $$1 }')

CPU_ONLY := 1
USE_OPENCV := 1
USE_LEVELDB := 1
USE_LMDB := 1
OPENCV_VERSION := $(_OCVMAJ)
BLAS := open
BLAS_INCLUDE := /usr/include
BLAS_LIB := /usr/lib
PYTHON_LIBRARIES := boost_python$(_PYMAJ) python$(_PYVER)
PYTHON_INCLUDE := /usr/include/python$(_PYVER) \
                  /usr/lib/python$(_PYVER)/site-packages/numpy/core/include
PYTHON_LIB := /usr/lib
WITH_PYTHON_LAYER := 1
INCLUDE_DIRS := $(PYTHON_INCLUDE)
LIBRARY_DIRS := $(PYTHON_LIB)
USE_PKG_CONFIG := 1
BUILD_DIR := build
DISTRIBUTE_DIR := distribute
TEST_GPUID := 0
Q ?= @
