_PYVER := $(shell python -c 'import sys; print("%s.%s" %sys.version_info[0:2])')
_PYMAJ := $(shell python -c 'import sys; print("%s" %sys.version_info[0])')
_OCVMAJ := $(shell opencv_version | awk -F'.' '{ print $$1 }')

USE_CUDNN := 1
USE_OPENCV := 1
USE_LEVELDB := 1
USE_LMDB := 1
OPENCV_VERSION := $(_OCVMAJ)
CUSTOM_CXX := /opt/cuda/bin/g++
CUDA_DIR := /opt/cuda
CUDA_ARCH := -gencode arch=compute_30,code=sm_30 \
             -gencode arch=compute_32,code=sm_32 \
             -gencode arch=compute_35,code=sm_35 \
             -gencode arch=compute_37,code=sm_37 \
             -gencode arch=compute_50,code=sm_50 \
             -gencode arch=compute_52,code=sm_52 \
             -gencode arch=compute_53,code=sm_53 \
             -gencode arch=compute_60,code=sm_60 \
             -gencode arch=compute_61,code=sm_61 \
             -gencode arch=compute_62,code=sm_62 \
             -gencode arch=compute_70,code=sm_70 \
             -gencode arch=compute_72,code=sm_72 \
             -gencode arch=compute_75,code=sm_75 \
             -gencode arch=compute_75,code=compute_75
BLAS := open
BLAS_INCLUDE := /usr/include
BLAS_LIB := /usr/lib
PYTHON_LIBRARIES := boost_python$(_PYMAJ) python$(_PYVER)
PYTHON_INCLUDE := /usr/include/python$(_PYVER) \
                  /usr/lib/python$(_PYVER)/site-packages/numpy/core/include
PYTHON_LIB := /usr/lib
WITH_PYTHON_LAYER := 1
INCLUDE_DIRS := $(PYTHON_INCLUDE)
LIBRARY_DIRS := $(PYTHON_LIB)
USE_NCCL := 1
USE_PKG_CONFIG := 1
BUILD_DIR := build
DISTRIBUTE_DIR := distribute
TEST_GPUID := 0
Q ?= @
