#!/bin/sh

_init() {
    variables=(  "G4NEUTRONHPDATA" \
                 "G4LEDATA" \
                 "G4LEVELGAMMADATA" \
                 "G4RADIOACTIVEDATA" \
                 "G4PARTICLEXSDATA" \
                 "G4PIIDATA" \
                 "G4REALSURFACEDATA" \
                 "G4SAIDXSDATA" \
                 "G4ABLADATA" \
                 "G4INCLDATA" \
                 "G4ENSDFSTATEDATA" \
                 "G4PARTICLEHPDATA" \  # not included by default anyway
                 "G4NEUTRONXS" \       # to be removed
              )

shell=("sh" "csh")

existing="existing"
path="/etc/profile.d"
}
_clean(){
    for _ext in ${shell[*]}
    do
        rm -f $existing.${_ext}
    done
}
_read() {
    _init
    for _varname in ${variables[*]}
    do
	if [ "$_varname" == "G4NEUTRONXS" ]   # to be removed
	then
	    continue
	fi
        for _ext in ${shell[*]}
        do
            sed -n /${_varname}/p ${path}/geant4.${_ext} >> $existing.${_ext}
	done
    done
}
_keep() {
    _init
    for _ext in ${shell[*]}
    do
        cat $existing.${_ext} >> ${path}/geant4.${_ext}
    done
    _clean
}

pre_upgrade() {
    _read
}
post_upgrade() {
    _keep
}
