post_install() {

# set the PETSC_DIR
source /etc/profile.d/petsc.sh
export PETSC_DIR=${PETSC_DIR}
#export PETSC_ARCH=${PETSC_ARCH}

noVersion=${1%%-[1-9]}
rootDir=${noVersion/_/-}

cat << EOF

If you just ran makepkg in this directory then
to test the PETSc installation you can run:

$ cd src/petsc-${rootDir}/; make PETSC_DIR=$PETSC_DIR test

EOF
}

post_upgrade() {
post_install
}

# vim:set ts=2 sw=2 et:
