'\" t
.\"     Title: PRAAT
.\"    Author: Rafael Laboissiere
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: April 22, 2013
.\"    Manual: User Commands
.\"    Source: Praat
.\"  Language: English
.\"
.TH "PRAAT" "1" "April 22, 2013" "Praat" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
praat \- doing phonetics by computer
.SH "SYNOPSIS"
.HP \w'\fBpraat\fR\ 'u
\fBpraat\fR
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBpraat\fR
command\&.
.PP
This manual page was written for the Debian distribution because the original program does not have a manual page\&.
.PP
\fBpraat\fR
is a program for speech analysis and synthesis\&. Through its graphical interface, several speech analysis functionalities are available: spectrograms, cochleograms, and pitch and formant extraction\&. Articulatory synthesis, as well as synthesis from pitch, formant, and intensity are also available\&. Other features are segmentation, labelling using the phonetic alphabet, and computation of statistics\&. Praat is configurable and extensible through its own scripting language and has provisions for communicating with other programs\&.
.SH "SEE ALSO"
.PP
\fBpraat\fR
has an on\-line documentation; just launch praat and look at the Help menu entry\&.
.PP
For further information, see the Praat website (http://www\&.praat\&.org)\&. A very good Beginner\*(Aqs Guide is available at http://www\&.ling\&.lu\&.se/persons/Sidney/praate/frames\&.html\&.
.SH "AUTHOR"
.PP
This manual page was written by Rafael Laboissiere <<rafael@laboissiere\&.net>> for the Debian system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 3 any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL\-3\&.
