# Contributor: Patrick Mischke

pkgname='python-ibm-cloud-sdk-core'
_name='ibm-cloud-sdk-core'
pkgver=3.17.2
pkgrel=2
pkgdesc="Core functionality required by Python code generated by the IBM Cloud OpenAPI SDK Generator"
url="https://github.com/IBM/python-sdk-core"
depends=('python-requests' 'python-dateutil' 'python-pyjwt')
makedepends=('python-setuptools')
license=('Apache')
arch=('any')
#source=("https://files.pythonhosted.org/packages/source/${_name::1}/$_name/$_name-$pkgver.tar.gz")
source=("https://github.com/IBM/python-sdk-core/archive/refs/tags/v${pkgver}.tar.gz")
sha256sums=('0772ee46b137bdc6439a194198a08ea11d332f0efb6ef69be1fe56b43d428dd7')

build() {
  cd "python-sdk-core-$pkgver"
  python setup.py build
}

package() {
  cd "python-sdk-core-$pkgver"
  python setup.py install --prefix=/usr --root="${pkgdir}" --optimize=1 --skip-build
  rm -rd "${pkgdir}/usr/lib/python3.11/site-packages/test"
  rm -rd "${pkgdir}/usr/lib/python3.11/site-packages/test_integration"
}
