post_install() {
  echo -e "\e[1;33m==>\e[0m Possible configurations in \e[1;31m/etc/pihole/pihole.toml\e[0m file"
  echo -e "\e[1;33m==>\e[0m Please read the instructions on the project page: \e[1;36mhttps://docs.pi-hole.net/ftldns/configfile/\e[0m"
}

post_upgrade() {
  # /etc/pihole/versions file generation
  [ -f /opt/pihole/updatecheck.sh ] && sudo -u pihole bash /opt/pihole/updatecheck.sh;

  post_install $1
}

post_remove() {
  /bin/true
}
