--- a/Makefile.am
+++ b/Makefile.am
@@ -133,9 +133,9 @@
   SMILE_CPPFLAGS = -Isrc/include -Iprogsrc/include $(SEMAINEAPI_CPPFLAGS) $(PORTAUDIO_CPPFLAGS) $(OPENCV_CPPFLAGS) -ggdb $(PTHREAD_CFLAGS)
   SMILE_LIBS =  $(PORTAUDIO_LDFLAGS) $(OPENCV_LDFLAGS) -lm $(SEMAINEAPI_LDFLAGS) $(PTHREAD_LIBS) $(DLIB)
    
-  SMILExtract_SOURCES = progsrc/smilextract/SMILExtract.cpp 
+  SMILExtract_SOURCES = progsrc/smilextract/SMILExtract.cpp ${SMILE_SOURCES}
   SMILExtract_CPPFLAGS = $(SMILE_CPPFLAGS)
-  SMILExtract_LDADD = $(SMILE_LIBS) -lopensmile
+  SMILExtract_LDADD = $(SMILE_LIBS)
 
   lib_LTLIBRARIES = libopensmile.la
   libopensmile_la_SOURCES = $(SMILE_SOURCES)
